include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    use_rethrow_when_possible: true
    prefer_const_declarations: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_put_required_named_parameters_first: true
    non_constant_identifier_names: true
    library_private_types_in_public_api: ignore
    unnecessary_brace_in_string_interps: true
    sized_box_for_whitespace: true

# If you plan on using Freezed in combination with json_serializable, recent versions of
# json_serializable and meta may require you to disable the invalid_annotation_target warning.
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"